import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Toaster } from "@/components/ui/Toaster";
import { cn } from "@/lib/utils";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
    lang='en' 
    className={cn(
      'bg-white text-slate-900 antialiased light', 
      inter.className)}>
      <body className='min-h-screen pt-12 bg-slate-50 antialiased'>
          <Providers>
            <NavBar />

            <div className='container max-w-7xl mx-auto h-full pt-12'>
              {children}
            </div>
            <Toaster />
          </Providers>
      </body>
    </html>
  )
}
